from fastapi import APIRouter, Depends, HTTPException, status
from asyncpg import Connection
from app.db.connection import get_db
from app.api.dependencies import get_current_student
from typing import Optional, List

router = APIRouter()

@router.get("/upcoming")
async def get_upcoming_discussions(department: str = 'Computer Science', section: str = 'A', conn: Connection = Depends(get_db)):
    # Fetch scheduled sessions for this department name/code and section name
    sessions = await conn.fetch("""
        SELECT ds.id, ds.discussion_date, ds.discussion_time, ds.group_size,
               ds.preparation_time_minutes, ds.discussion_duration_minutes, ds.status,
               d.name as department_name, sec.name as section_name
        FROM discussion_sessions ds
        JOIN departments d ON ds.department_id = d.id
        JOIN sections sec ON ds.section_id = sec.id
        WHERE (d.name = $1 OR d.code = $1)
          AND (sec.name = $2 OR sec.name = 'Section ' || $2 OR 'Section ' || sec.name = $2)
          AND ds.status = 'SCHEDULED'
        ORDER BY ds.discussion_date ASC, ds.discussion_time ASC
    """, department, section)

    result = []
    for r in sessions:
        # Check if a group topic exists
        topic_title = "Topic will be generated by AI"
        group_row = await conn.fetchrow("""
            SELECT dt.title 
            FROM discussion_groups dg
            JOIN discussion_topics dt ON dg.topic_id = dt.id
            WHERE dg.session_id = $1 LIMIT 1
        """, r["id"])
        if group_row:
            topic_title = group_row["title"]

        result.append({
            "id": str(r["id"]),
            "status": r["status"],
            "title": topic_title,
            "topic": topic_title,
            "department": r["department_name"],
            "section": r["section_name"],
            "scheduled_time": f"{r['discussion_date']}T{r['discussion_time']}",
            "groupSize": r["group_size"],
            "prepTime": r["preparation_time_minutes"],
            "duration": r["discussion_duration_minutes"]
        })
    return result

@router.get("/history")
async def get_discussion_history(student_id: Optional[str] = None, current_student: dict = Depends(get_current_student), conn: Connection = Depends(get_db)):
    # Prioritize authenticated student ID
    target_student_id = current_student["id"] if current_student else student_id
    if not target_student_id:
        raise HTTPException(status_code=401, detail="Authentication required")

    history = await conn.fetch("""
        SELECT dg.id as group_id, ds.id as session_id, dg.group_number, ds.discussion_date, ds.discussion_time, ds.status,
               dt.title as topic_title,
               sc.grammar_score, sc.fluency_score, sc.confidence_score, sc.overall_score
        FROM group_members gm
        JOIN discussion_groups dg ON gm.group_id = dg.id
        JOIN discussion_sessions ds ON dg.session_id = ds.id
        LEFT JOIN discussion_topics dt ON dg.topic_id = dt.id
        LEFT JOIN student_scores sc ON dg.id = sc.group_id AND gm.student_id = sc.student_id
        WHERE gm.student_id = $1 AND ds.status = 'COMPLETED'
        ORDER BY ds.discussion_date DESC, ds.discussion_time DESC
    """, target_student_id)
    
    result = []
    for r in history:
        avg = float(r["overall_score"]) if r["overall_score"] is not None else None
        if avg is None and r["grammar_score"] is not None:
            avg = (float(r["grammar_score"]) + float(r["fluency_score"]) + float(r["confidence_score"])) / 3.0
            
        result.append({
            "id": str(r["session_id"]),
            "group": r["group_number"],
            "scheduled_time": f"{r['discussion_date']}T{r['discussion_time']}",
            "topic": r["topic_title"] or "Group Discussion",
            "grammar_score": round(avg) if avg is not None else None,
            "status": r["status"]
        })
    return result
