import React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, Clock, Users, Timer, ArrowRight, BookOpen } from "lucide-react";
import { motion } from "framer-motion";
import { itemVariants } from "@/components/PageWrapper";

interface UpcomingDiscussionsProps {
  onJoin: () => void;
  sessions: any[];
}

export default function UpcomingDiscussions({ onJoin, sessions }: UpcomingDiscussionsProps) {
  const [countdown, setCountdown] = React.useState(4542); // 01:15:42 in seconds

  React.useEffect(() => {
    const timer = setInterval(() => {
      setCountdown(prev => (prev > 0 ? prev - 1 : 0));
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (totalSeconds: number) => {
    const h = Math.floor(totalSeconds / 3600);
    const m = Math.floor((totalSeconds % 3600) / 60);
    const s = totalSeconds % 60;
    return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  return (
    <div className="space-y-6">
      <motion.div variants={itemVariants} className="bg-indigo-50 border border-indigo-100 rounded-xl p-6 flex flex-col md:flex-row items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-indigo-900">Upcoming Live Discussions</h2>
          <p className="text-indigo-700 mt-1">
            Join your scheduled AI-moderated group discussions to improve your communication skills and earn XP.
          </p>
        </div>
        <div className="bg-white p-3 rounded-lg shadow-sm border border-indigo-100 text-center flex-shrink-0 min-w-[150px]">
          <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-1">Next Session In</div>
          <div className="text-2xl font-bold text-indigo-600 font-mono">{formatTime(countdown)}</div>
        </div>
      </motion.div>

      <motion.div variants={itemVariants} className="grid grid-cols-1 gap-6">
        {sessions.map((session, idx) => (
          <Card key={idx} className="shadow-md hover:shadow-lg transition-shadow border-l-4 border-l-indigo-500">
            <CardHeader className="pb-3 border-b border-slate-100">
              <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4">
                <div>
                  <div className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-indigo-100 text-indigo-800 mb-2">
                    {session.status}
                  </div>
                  <CardTitle className="text-xl">{session.topic || "Topic will be generated by AI"}</CardTitle>
                  <CardDescription className="text-slate-600 font-medium mt-1">
                    {session.department} • {session.year} • {session.section}
                  </CardDescription>
                </div>
                <Button onClick={onJoin} className="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 shadow-md transition-all hover:scale-105 group">
                  Join Discussion <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </div>
            </CardHeader>
            <CardContent className="pt-4">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-slate-50 rounded-lg"><Calendar className="w-4 h-4 text-slate-500" /></div>
                  <div>
                    <div className="text-xs text-slate-500">Date</div>
                    <div className="text-sm font-medium">{session.date}</div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-slate-50 rounded-lg"><Clock className="w-4 h-4 text-slate-500" /></div>
                  <div>
                    <div className="text-xs text-slate-500">Time</div>
                    <div className="text-sm font-medium">{session.time}</div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-slate-50 rounded-lg"><Users className="w-4 h-4 text-slate-500" /></div>
                  <div>
                    <div className="text-xs text-slate-500">Group Size</div>
                    <div className="text-sm font-medium">{session.groupSize} Students</div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <div className="p-2 bg-slate-50 rounded-lg"><Timer className="w-4 h-4 text-slate-500" /></div>
                  <div>
                    <div className="text-xs text-slate-500">Duration</div>
                    <div className="text-sm font-medium">{session.prepTime}m Prep • {session.duration}m Live</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}

        {sessions.length === 0 && (
          <div className="text-center py-12 bg-white rounded-xl border border-dashed border-slate-300">
            <BookOpen className="w-12 h-12 text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg font-medium text-slate-900">No Upcoming Discussions</h3>
            <p className="text-slate-500 mt-1">Check back later or contact your department admin.</p>
          </div>
        )}
      </motion.div>
    </div>
  );
}
